### PR TITLE
Update OvalBuilder.java dependency comment

### PR DESCRIPTION
**Pull request by cadunne**

### CODE REVIEW

**Comment by BrandonArp** [comment]
Sorry, I somehow missed this PR.  Is the javassist dependency required?  I understand that using our javassist maven plugin will result in the OvalBuilder being woven at compile time, but there was never an intention to require the javassist library a runtime.

**Comment by cadunne** [comment]
Hey, I'm not 100 percent sure, at some point though our code base would no
longer compile and explicitly declaring this dependency fixed the issue. I
would check with Ville to be sure.

**Comment by vjkoskela** [comment]
The Javassist Maven Core dependency is the library portion of the Maven Plugin that we developed. In particular, it contains the annotation used to detect whether the code was woven by a previous pass of the plugin. We are already depending on this at runtime in commons and mad:

https://github.com/ArpNetworking/commons/blob/master/pom.xml#L243
https://github.com/ArpNetworking/metrics-aggregator-daemon/blob/master/pom.xml#L543

**Comment by vjkoskela** [comment]
So the arpnetworking javassist core does depend on javassist itself; namely here:

https://github.com/ArpNetworking/maven-javassist/blob/master/maven-javassist-core/src/main/java/com/arpnetworking/commons/maven/javassist/ClassProcessor.java

Namely, the dependency on CtClass. This interface is used by packages which implement a processor to process classes. ArpNetworking commons contains such a class, and therefore must have a dependency when using that processor on our core library (and therefore javassist).

The dependency model in commons is provided, so only users of this class are expected to add the dependency to their poms (as we have done in our projects using this class). This PR only impacts correctness of dependency documentation. My vote would be to accept it, and we can work on removing that dependency, although the only real option I can see is to either:

A) Push provided down a level and include transitive dependencies above. Projects invoking the weaver will only need Arpnetworking javassist core and not actual javassist although they will pick this up transitively through whatever project has the weaver in it.

B) Split the Arpnetworking javassist core into two projects: the runtime and the weaver. However, this has the same problem as above. 

The solution would then be to declare the weaver part as a plugin dependency. So either of these seems possible, but it's going to be some work and not really a fault with this MR.

**Comment by BrandonArp** [comment]
This problem was addressed in #59 and the dependency should no longer be required.

**Pull request closed without merging**
